userdata:
  image: busybox
  volumes:
   - /home/user
  entrypoint: /bin/true

cups:
  image: reto/cupsserver
  restart: unless-stopped
  
thunderbird:
  image: reto/thunderbird
  restart: unless-stopped
  links:
   - cups:printserver
  volumes_from:
   - userdata
  ports:
   - "2020:22"
   
 
   